# Generated by Django 5.1.1 on 2025-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedBarcode',
            fields=[
                ('scannedBarcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('scannedBy', models.CharField(max_length=40)),
                ('medicineName', models.CharField(max_length=100)),
                ('usedFor', models.CharField(max_length=400)),
            ],
        ),
    ]
